### ISSUE TITLE
How to authenticate using JWT

### ISSUE THREAD

**Issue by rakeshpatra** [smooch/smooch-desk#41]
Since my app is already using JWT for authentication, I'm unable to authenticate using key_id and secret, getting the following error, let me know if any solution for this is included in the code.

> Exception while invoking method 'getIntegrations' Error: Invalid JWT body. Cannot use account scope with app secret key

**Comment by alavers** [comment]
Smooch has different levels of API keys. In this case, Smoch Desk is expecting account scope, so please make sure you're using account level keys, found here: https://app.smooch.io/account. You can find more info on this [here](https://docs.smooch.io/rest/#authorization)
